blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.BlogIndex.as_view(), name='index'),
    url(r"^(?P<pk>[0-9]+)/tag/$", views.blogTag, name='tag'),
    url(r"^blog/(?P<pk>[0-9]+)$", views.BlogPost.as_view(), name='blogpost')

]

django_blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include("blog.urls",namespace="blog")),
    url('^markdown/', include( 'django_markdown.urls')),
]

blog/models.py
from django.db import models
from django_markdown.models import MarkdownField
# Create your models her


class Tag(models.Model):
    question_text = models.CharField(max_length=10)
    def __str__(self):
        return self.question_text


class MyBlog(models.Model):
    tittle = models.CharField(max_length=50,default="")
    tittle_sm = models.CharField(max_length=50,default="")
    body = MarkdownField(default="")
    pub_date = models.DateTimeField(auto_now=True,blank=True)
    publisher = models.BooleanField(default=False)
    tag = models.ForeignKey(Tag)
    def __str__(self):
        return self.tittle

blog/views.py
from django.shortcuts import render
from django.views import generic
from . import models
from .models import Tag,MyBlog

# Create your views here.


def index(request):
    return render(request, 'blog/index.html', )

class BlogIndex(generic.ListView):
    queryset = models.MyBlog.objects.filter(publisher="True").order_by("-pub_date")
    template_name = "blog/index.html"
    paginate_by = 2


class BlogPost(generic.DetailView):
    model = MyBlog
    template_name = "blog/blogpost.html"




def blogTag(request,pk):
    queryset=models.Tag.objects.get(id=pk).myblog_set.all().filter(publisher="True").order_by("-pub_date")
    context = {"queryset":queryset}
    return render(request,"blog/blogtag.html",context)

blog/templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html>
	<head>
		<title>秦客隨便說</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="{% static 'blog/assets/js/ie/html5shiv.js' %}"></script><![endif]-->
		<link rel="stylesheet" href="{% static 'blog/assets/css/main.css' %}" />
		<!--[if lte IE 8]><link rel="stylesheet" href="{% static 'blog/assets/css/ie8.css' %}" /><![endif]-->
	</head>
	<body>
    {% block index %}
    {% endblock %}


    {% include "blog/nav.html" %}



			<script src="{% static 'blog/assets/js/jquery.min.js' %}"></script>
			<script src="{% static 'blog/assets/js/skel.min.js' %}"></script>
			<script src="{% static 'blog/assets/js/util.js' %}"></script>
			<!--[if lte IE 8]><script src="{% static 'blog/assets/js/ie/respond.min.js' %}"></script><![endif]-->
			<script src="{% static 'blog/assets/js/main.js' %}"></script>

	</body>
</html>

blog/templates/blog/blogpost.html
{% extends "blog/base.html" %}
{% load django_markdown %}
{% block index %}



		<!-- Content -->
			<div id="content">
				<div class="inner">

					<!-- Post -->
						<article class="box post post-excerpt">
							<header>

								<h2><a href="#">{{ myblog.tittle }}</a></h2>
								<p>{{ myblog.tittle_sm }}</p>
							</header>
							<div class="info">

								<span class="date"> <span class="day">{{ myblog.pub_date.day }}</span><span class="month">{{ myblog.pub_date.month }}月</span><span class="year">, {{ myblog.pub_date.year }}年</span></span>

								<ul class="stats">
{#									<li><a href="#" class="icon fa-comment">16</a></li>#}
{#									<li><a href="#" class="icon fa-heart">32</a></li>#}
{#									<li><a href="#" class="icon fa-twitter">64</a></li>#}
{#									<li><a href="#" class="icon fa-facebook">128</a></li>#}
								</ul>
							</div>
{#							<a href="#" class="image featured"><img src="{% static 'blog/images/pic01.jpg' %}" alt="" /></a>#}
							<p>{{ myblog.body|markdown}}</p>
						</article>


					<!-- Pagination -->
{#						<div class="pagination">#}
{#							<!--<a href="#" class="button previous">Previous Page</a>-->#}
{#                             {% if page_obj.has_previous %}#}
{#                                 <a href="?page={{ page_obj.previous_page_number }}" class="button next">上一頁</a>#}
{#                             {% endif %}#}
{#							<div class="pages">#}
{#								{{ page_obj.number }} 頁 / {{ paginator.num_pages }}頁#}
{#							</div>#}
{#                            {% if page_obj.has_next %}#}
{#							    <a href="?page={{ page_obj.next_page_number }}" class="button next">下一頁</a>#}
{#                            {% endif %}#}
{#						</div>#}

				</div>
			</div>



{% endblock %}

blog/templates/blog/blogtag.html
{% extends "blog/base.html" %}
{% load django_markdown %}
{% block index %}



		<!-- Content -->
			<div id="content">
				<div class="inner">

					<!-- Post -->
                        {% for post in queryset %}
						<article class="box post post-excerpt">
							<header>

								<h2><a href="{% url 'blog:blogpost' pk=post.id %}">{{ post.tittle }}</a></h2>
								<p>{{ post.tittle_sm }}</p>
                                <span class="date"> <span class="day">{{ post.pub_date.day }}</span><span class="month">{{ post.pub_date.month }}月</span><span class="year">, {{ post.pub_date.year }}年</span></span>

							</header>
{#							<div class="info">#}
{##}
{#								<span class="date"> <span class="day">{{ post.pub_date.day }}/ㄊ</span><span class="month">{{ post.pub_date.month }}月</span><span class="year">, {{ post.pub_date.year }}年</span></span>#}
{##}
{#								<ul class="stats">#}
{#									<li><a href="#" class="icon fa-comment">16</a></li>#}
{#									<li><a href="#" class="icon fa-heart">32</a></li>#}
{#									<li><a href="#" class="icon fa-twitter">64</a></li>#}
{#									<li><a href="#" class="icon fa-facebook">128</a></li>#}
{#								</ul>#}
{#							</div>#}
{#							<a href="#" class="image featured"><img src="{% static 'blog/images/pic01.jpg' %}" alt="" /></a>#}
{#							<p>{{ post.body|markdown}}</p>#}
						</article>
                        {% endfor %}

{#					<!-- Pagination -->#}
{#						<div class="pagination">#}
{#							<!--<a href="#" class="button previous">Previous Page</a>-->#}
{#                             {% if page_obj.has_previous %}#}
{#                                 <a href="?page={{ page_obj.previous_page_number }}" class="button next">上一頁</a>#}
{#                             {% endif %}#}
{#							<div class="pages">#}
{#								{{ page_obj.number }} 頁 / {{ paginator.num_pages }}頁#}
{#							</div>#}
{#                            {% if page_obj.has_next %}#}
{#							    <a href="?page={{ page_obj.next_page_number }}" class="button next">下一頁</a>#}
{#                            {% endif %}#}
{#						</div>#}

				</div>
			</div>



{% endblock %}

blog/templates/blog/index.html
{% extends "blog/base.html" %}
{% load django_markdown %}
{% block index %}



		<!-- Content -->
			<div id="content">
				<div class="inner">

					<!-- Post -->
                        {% for post in object_list %}
						<article class="box post post-excerpt">
							<header>

								<h2><a href="{% url 'blog:blogpost' pk=post.id %}">{{ post.tittle }}</a></h2>
								<p>{{ post.tittle_sm }}</p><a href="{% url 'blog:tag' pk=post.tag.id %}">{{ post.tag }}</a>
							</header>
							<div class="info">

								<span class="date"> <span class="day">{{ post.pub_date.day }}</span><span class="month">{{ post.pub_date.month }}月</span><span class="year">, {{ post.pub_date.year }}年</span></span>

								<ul class="stats">
{#									<li><a href="#" class="icon fa-comment">16</a></li>#}
{#									<li><a href="#" class="icon fa-heart">32</a></li>#}
{#									<li><a href="#" class="icon fa-twitter">64</a></li>#}
{#									<li><a href="#" class="icon fa-facebook">128</a></li>#}
								</ul>
							</div>
{#							<a href="#" class="image featured"><img src="{% static 'blog/images/pic01.jpg' %}" alt="" /></a>#}
							<p>{{ post.body|markdown}}</p>
						</article>
                        {% endfor %}

					<!-- Pagination -->
						<div class="pagination">
							<!--<a href="#" class="button previous">Previous Page</a>-->
                             {% if page_obj.has_previous %}
                                 <a href="?page={{ page_obj.previous_page_number }}" class="button next">上一頁</a>
                             {% endif %}
							<div class="pages">
								{{ page_obj.number }} 頁 / {{ paginator.num_pages }}頁
							</div>
                            {% if page_obj.has_next %}
							    <a href="?page={{ page_obj.next_page_number }}" class="button next">下一頁</a>
                            {% endif %}
						</div>

				</div>
			</div>



{% endblock %}

blog/templates/blog/nav.html
<!-- Sidebar -->

			<div id="sidebar">

				<!-- Logo -->
					<h1 id="logo"><a>隨便說說</a></h1>

				<!-- Nav -->
					<nav id="nav">
						<ul>
							<li class="current"><a href="{% url 'blog:index' %}">首頁</a></li>
							<li><a href="{% url 'blog:tag' pk=1%}">生活雜談</a></li>
							<li><a href="{% url 'blog:tag' pk=2%}">讀書亂談</a></li>
                            <li><a href="{% url 'blog:tag' pk=3%}">程式學習</a></li>
						</ul>
					</nav>

				<!-- Search -->
{#					<section class="box search">#}
{#						<form method="post" action="#">#}
{#							<input type="text" class="text" name="search" placeholder="Search" />#}
{#						</form>#}
{#					</section>#}

				<!-- Text -->
					<section class="box text-style1">
						<div class="inner">
							<p>
								<strong>秦客說:</strong> 一個月減一公斤，十二個月也只能減十二公斤啊
							</p>
						</div>
					</section>

				<!-- Recent Posts -->
{#					<section class="box recent-posts">#}
{#						<header>#}
{#							<h2>Recent Posts</h2>#}
{#						</header>#}
{#						<ul>#}
{#                            {% for list in object_list %}#}
{#							<li><a href="#">{{ list.tittle }}</a></li>#}
{#                            {% endfor %}#}
{#							<li><a href="#">Feugiat nisl aliquam</a></li>#}
{#							<li><a href="#">Sed dolore magna</a></li>#}
{#							<li><a href="#">Malesuada commodo</a></li>#}
{#							<li><a href="#">Ipsum metus nullam</a></li>#}
{#						</ul>#}
{#					</section>#}

				<!-- Recent Comments -->
{#					<section class="box recent-comments">#}
{#						<header>#}
{#							<h2>Recent Comments</h2>#}
{#						</header>#}
{#						<ul>#}
{#							<li>case on <a href="#">Lorem ipsum dolor</a></li>#}
{#							<li>molly on <a href="#">Sed dolore magna</a></li>#}
{#							<li>case on <a href="#">Sed dolore magna</a></li>#}
{#						</ul>#}
{#					</section>#}

				<!-- Calendar -->
					<section class="box calendar">
						<div class="inner">
							<table>
{#								<caption>歡迎聯絡</caption>#}
								<thead>
									<tr>
										<th scope="col" title="Monday">關於作者</th>
									</tr>
                                </thead>
                                <tr  >
                                    <div align=center>
                                    <a href="https://www.facebook.com/weilongchin">
                                        <img class="img" align=center src="https://badge.facebook.com/badge/100000045396834.3195.730971856.png"  />
                                    </a>
                                    </div>
                                    <br />
                                </tr>



							</table>
						</div>
					</section>

				<!-- Copyright -->
					<ul id="copyright">
						<li>連絡信箱: </li><li><a href="">weilongchin@gmail.com</a></li>
					</ul>

			</div>